### ISSUE TITLE
undefined error

### ISSUE THREAD

**Issue by aavileli** [markitx/dynamo-backup-to-s3#10]
Output:
Starting to copy table db_test
Error backing up undefined
undefined
Error backing up db_test
[Error: Cannot initiate transfer]
Done copying table db_test
Finished backup
Error backing up undefined
undefined
Error backing up db_test
[Error: Cannot initiate transfer]
Done copying table db_test
nodejs/dynamodb/node_modules/dynamo-backup-to-s3/node_modules/s3-streaming-upload/node_modules/aws-sdk/lib/request.js:30
            throw err;
                  ^
Error: Callback was already called.
    at nodejs/dynamodb/node_modules/dynamo-backup-to-s3/node_modules/async/lib/async.js:30:31
    at nodejs/dynamodb/node_modules/dynamo-backup-to-s3/lib/dynamo-backup.js:119:21
    at Uploader.<anonymous> (nodejs/dynamodb/node_modules/dynamo-backup-to-s3/lib/dynamo-backup.js:63:16)
    at Uploader.emit (events.js:107:17)
    at Response.<anonymous> (nodejs/dynamodb/node_modules/dynamo-backup-to-s3/node_modules/s3-streaming-upload/lib/uploader.js:71:17)
    at Request.<anonymous> (nodejs/dynamodb/node_modules/dynamo-backup-to-s3/node_modules/s3-streaming-upload/node_modules/aws-sdk/lib/request.js:353:18)
    at Request.callListeners (nodejs/dynamodb/node_modules/dynamo-backup-to-s3/node_modules/s3-streaming-upload/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (nodejs/dynamodb/node_modules/dynamo-backup-to-s3/node_modules/s3-streaming-upload/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (nodejs/dynamodb/node_modules/dynamo-backup-to-s3/node_modules/s3-streaming-upload/node_modules/aws-sdk/lib/request.js:595:14)
    at Request.transition (nodejs/dynamodb/node_modules/dynamo-backup-to-s3/node_modules/s3-streaming-upload/node_modules/aws-sdk/lib/request.js:21:10)

Script :

var DynamoBackup = require('dynamo-backup-to-s3');

var backup = new DynamoBackup({
    includedTables: ['db_test'],
    bucket: "dynamodb-backup",
    awsAccessKey: "xxxxx",
    awsSecretKey: "xxxxx",
    awsRegion: "us-west-1"
});

backup.on('error', function(data) {
    console.log('Error backing up ' + data.tableName);
    console.log(data.error);
});

backup.on('start-backup', function(tableName) {
    console.log('Starting to copy table ' + tableName);
});

backup.on('end-backup', function(tableName) {
    console.log('Done copying table ' + tableName);
});

backup.backupAllTables(function() {
      console.log("Finished backup");
});

Modules:-

└─┬ dynamo-backup-to-s3@0.1.9
  ├── async@0.9.2
  ├─┬ aws-sdk@2.0.31
  │ ├─┬ xml2js@0.2.6
  │ │ └── sax@0.4.2
  │ └── xmlbuilder@0.4.2
  ├── commander@2.5.1
  ├── moment@2.8.4
  ├─┬ s3-streaming-upload@0.1.17
  │ ├─┬ aws-sdk@2.1.50
  │ │ ├── sax@0.5.3
  │ │ ├── xml2js@0.2.8
  │ │ └── xmlbuilder@0.4.2
  │ └─┬ readable-stream@1.0.33
  │   ├── core-util-is@1.0.1
  │   ├── inherits@2.0.1
  │   ├── isarray@0.0.1
  │   └── string_decoder@0.10.31
  └── underscore@1.7.0

**Comment by dylanlingelbach** [comment]
@aavileli - can you change the error handler to:

```
backup.on('error', function(data) {
  console.log('Error backing up ' + data.tableName);
  console.log(data);
});
```

and respond with the output?

**Comment by aavileli** [comment]
@dylanlingelbach  I think there is some issue in the s3-streaming-upload it works some time some times does not so I moved away and implemented the solution using https://github.com/mapbox/dyno and some unix paralel to upload to s3 using shell

**Comment by dylanlingelbach** [comment]
@aavileli - sorry to hear it wasn't working for you. I wasn't able to reproduce this, and I can't tell what is going on from the information provided.

I'll close for now, but feel free to reopen if you can provide more info here.
