### ISSUE TITLE
[Cannot Initiate Transfer]

### ISSUE THREAD

**Issue by GreyEcologist** [markitx/dynamo-backup-to-s3#12]
Hey, I'm getting this error, I'm wondering if it's policy issue, I have full access for S3 and DynamoDB, do I need other permissions?

here's the error below ( i added some console.logs to see where the error was) :

```
START RequestId: 3e9af9a8-9ada-11e5-84fb-d732598ecf7e Version: $LATEST
2015-12-04T22:56:25.049Z    3e9af9a8-9ada-11e5-84fb-d732598ecf7e    backupTable failed celebInfo error is Error: Cannot initiate transfer
2015-12-04T22:56:25.049Z    3e9af9a8-9ada-11e5-84fb-d732598ecf7e    Error backing up undefined
2015-12-04T22:56:25.066Z    3e9af9a8-9ada-11e5-84fb-d732598ecf7e    backupAllTables failed error is Error: Cannot initiate transfer
2015-12-04T22:56:25.066Z    3e9af9a8-9ada-11e5-84fb-d732598ecf7e    Error backing up celebInfo
2015-12-04T22:56:25.066Z    3e9af9a8-9ada-11e5-84fb-d732598ecf7e    [Error: Cannot initiate transfer]
2015-12-04T22:56:25.068Z    3e9af9a8-9ada-11e5-84fb-d732598ecf7e    Error: Callback was already called.
    at /var/task/node_modules/dynamo-backup-to-s3/node_modules/async/lib/async.js:30:31
    at /var/task/node_modules/dynamo-backup-to-s3/lib/dynamo-backup.js:126:36
    at Uploader.<anonymous> (/var/task/node_modules/dynamo-backup-to-s3/lib/dynamo-backup.js:65:16)
    at Uploader.emit (events.js:95:17)
    at Response.<anonymous> (/var/task/node_modules/dynamo-backup-to-s3/node_modules/s3-streaming-upload/lib/uploader.js:71:17)
    at Request.<anonymous> (/var/task/node_modules/dynamo-backup-to-s3/node_modules/s3-streaming-upload/node_modules/aws-sdk/lib/request.js:353:18)
    at Request.callListeners (/var/task/node_modules/dynamo-backup-to-s3/node_modules/s3-streaming-upload/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/var/task/node_modules/dynamo-backup-to-s3/node_modules/s3-streaming-upload/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/task/node_modules/dynamo-backup-to-s3/node_modules/s3-streaming-upload/node_modules/aws-sdk/lib/request.js:595:14)
    at Request.transition (/var/task/node_modules/dynamo-backup-to-s3/node_modules/s3-streaming-upload/node_modules/aws-sdk/lib/request.js:21:10)
END RequestId: 3e9af9a8-9ada-11e5-84fb-d732598ecf7e
REPORT RequestId: 3e9af9a8-9ada-11e5-84fb-d732598ecf7e  Duration: 208.05 ms Billed Duration: 300 ms     Memory Size: 256 MB Max Memory Used: 19 MB  
Process exited before completing request
```

**Comment by GreyEcologist** [comment]
by the way, I traced the error to a function inside the uploader.js:
```
  Uploader.prototype.initiateTransfer = function() {
    var _this = this;
    if (this.initializing === false) {
      this.initializing = true;
      return this.getNewClient().createMultipartUpload(this.objectParams, function(err, data) {
        _this.initializing = false;
        if (err) {
          _this.emit('failed', new Error("Cannot initiate transfer"));
          _this.emit('error', err);
          return typeof _this.cb === "function" ? _this.cb(err) : void 0;
        }
        _this.uploadId = data.UploadId;
        _this.initiated = true;
        return _this.emit('initiated', _this.uploadId);
      });
    }
  };
```
the error itself is: 
```Callback was already called```

**Comment by GreyEcologist** [comment]
I wish I could do more to help, I'm new to node.js and npm, the issue with the line 71 with the createMultipartUpload in the uploader, and this thread suggests it might a version issue with the modules:
https://github.com/apiaryio/s3-streaming-upload/issues/17

this is what my npm module tree looks like:
```
├── async@0.9.2
├─┬ aws-sdk@2.0.31
│ ├─┬ xml2js@0.2.6
│ │ └── sax@0.4.2
│ └── xmlbuilder@0.4.2
├── commander@2.5.1
├── moment@2.8.4
├─┬ s3-streaming-upload@0.1.17
│ ├─┬ aws-sdk@2.1.50
│ │ ├── sax@0.5.3
│ │ ├── xml2js@0.2.8
│ │ └── xmlbuilder@0.4.2
│ └─┬ readable-stream@1.0.33
│   ├── core-util-is@1.0.2
│   ├── inherits@2.0.1
│   ├── isarray@0.0.1
│   └── string_decoder@0.10.31
└── underscore@1.7.0
```

the AWS sdk is present under two version, could that be it?

**Comment by dylanlingelbach** [comment]
@GreyEcologist - I just pushed a new version 0.3.0 that uses a more recent version of the AWS SDK. Can you try that version?

**Comment by GreyEcologist** [comment]
Thanks. I'm getting a different kind of issue now:

```
Starting to copy table celebInfo
2015-12-08T04:09:14.975Z    70ae5588-9d61-11e5-84c0-b5050315e51c    { [SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.]
  message: 'The request signature we calculated does not match the signature you provided. Check your key and signing method.',
  code: 'SignatureDoesNotMatch',
  time: Tue Dec 08 2015 04:09:14 GMT+0000 (UTC),
  statusCode: 403,
  retryable: false,
  retryDelay: 30 } undefined
2015-12-08T04:09:14.977Z    70ae5588-9d61-11e5-84c0-b5050315e51c    undefined
2015-12-08T04:09:14.994Z    70ae5588-9d61-11e5-84c0-b5050315e51c    Done copying table celebInfo
2015-12-08T04:09:14.994Z    70ae5588-9d61-11e5-84c0-b5050315e51c    Finished backing up DynamoDB
END RequestId: 70ae5588-9d61-11e5-84c0-b5050315e51c
```

I tried creating and using a new access key, but same thing.

**Comment by GreyEcologist** [comment]
same thing:

```
2015-12-08T07:25:47.676Z	e5a17f6e-9d7c-11e5-aa8e-1dd9b5dce6de	Starting to copy table celebInfo
2015-12-08T07:25:48.553Z	e5a17f6e-9d7c-11e5-aa8e-1dd9b5dce6de	{ [SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.]
  message: 'The request signature we calculated does not match the signature you provided. Check your key and signing method.',
  code: 'SignatureDoesNotMatch',
  time: Tue Dec 08 2015 07:25:48 GMT+0000 (UTC),
  statusCode: 403,
  retryable: false,
  retryDelay: 30 } undefined
2015-12-08T07:25:48.555Z	e5a17f6e-9d7c-11e5-aa8e-1dd9b5dce6de	undefined
2015-12-08T07:25:48.555Z	e5a17f6e-9d7c-11e5-aa8e-1dd9b5dce6de	Done copying table celebInfo
2015-12-08T07:25:48.555Z	e5a17f6e-9d7c-11e5-aa8e-1dd9b5dce6de	Finished backing up DynamoDB
END RequestId: e5a17f6e-9d7c-11e5-aa8e-1dd9b5dce6de
```

**Comment by dylanlingelbach** [comment]
@GreyEcologist - did you do an `npm install` after upgrading the package version? Can you try working through these steps: http://docs.aws.amazon.com/general/latest/gr/signature-v4-troubleshooting.html?

Are you passing the access key and secret to the backup class or using `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` as environment variables?

**Comment by dylanlingelbach** [comment]
Closing for now. @GreyEcologist let me know if you continue to have issues
