### ISSUE TITLE
Unexpected end of input - restorartion

### ISSUE THREAD

**Issue by KarolJunde** [markitx/dynamo-backup-to-s3#73]
Under the test I've tried to restore a table(200Mb - 525k items) from S3 using your tool, however, I came across info pasted below. Making changes in concurrency hasn't resolved the case. I would be grateful if you were able to point the cause and how it should be mitigated.

./bin/dynamo-restore-from-s3 -t ProductRR -c 200 -s s3://xxx/xxx/Products.json --readcapacity 200 --writecapacity 200 --aws-region eu-central-1 --partitionkey Id
...
Batch sent. 51 in flight. 213Mb remaining to download...
Batch sent. 52 in flight. 213Mb remaining to download...
Batch sent. 53 in flight. 213Mb remaining to download...
Batch sent. 54 in flight. 213Mb remaining to download...
undefined:1
{"YPosition":{"S":"55e4fb166e18335069f9b21783a222"},"Title":{"S":"a6643fda61abf5c7d34f"},"PageCount":{"S":"6374237438b50df9ee129b5c22d3c1746"},"Dimensions":{"S":"96a1d5a24bb982406397

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at DynamoRestore._processLine (/home/nubes/dynamo-backup-to-s3/lib/dynamo-restore.js:173:55)
    at emitOne (events.js:77:13)
    at Interface.emit (events.js:169:7)
    at PassThrough.onend (readline.js:92:12)
    at emitNone (events.js:72:20)
    at PassThrough.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickDomainCallback (node.js:396:17)

**Comment by iammohan83** [comment]
I am getting the same issue. Do you find fix for this issue. I am trying to restore 10 GB.
