### ISSUE TITLE
TypeError: Cannot read property push of undefined on dynamo-restore-from-s3

### ISSUE THREAD

**Issue by SebastianWendel** [markitx/dynamo-backup-to-s3#84]
Hi Mark,

thanks for taking the time and writing that pice of software.

Backup works find and i'm now able to backup to another colo.

Regarding the restore i run into some trouble. If i try the following:

```
bin/dynamo-restore-from-s3 --source 's3://XXXXXXXXXXXXXXXXXXXX/20180919_1611/XXXXXXXXXXXXXXXXXXXX-XXXXXXXXXXXXX.json' --table 'XXXXXXXXXXXXXXXXXXXX-XXXXXXXXXXXXX' --overwrite --aws-region eu-central-1 --aws-key 'XXXXXXXXXXXXXXXXXXXX' --aws-secret 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
```

i get this error ...

```
WARN: table [XXXXXXXXXXXXXXXXXXXX-XXXXXXXXXXXXX] will be overwritten.
Starting download. 0Kb remaining...
node_modules/dynamo-backup-to-s3/lib/dynamo-restore.js:148
                this.batches.push({
                             ^

TypeError: Cannot read property 'push' of undefined
    at DynamoRestore.<anonymous> (/home/hans/Development/mtribes/backup-service/node_modules/dynamo-backup-to-s3/lib/dynamo-restore.js:148:30)
    at Interface.emit (events.js:187:15)
    at Interface.EventEmitter.emit (domain.js:442:20)
    at Interface.close (readline.js:379:8)
    at PassThrough.onend (readline.js:157:10)
    at PassThrough.emit (events.js:182:13)
    at PassThrough.EventEmitter.emit (domain.js:442:20)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Any idea whats going wrong?

Thanks and Regards,
Sebastian

**Comment by timestopper** [comment]
Hi @sourceindex, you can use my fork, this issue is fixed there:
https://github.com/timestopper/dynamo-backup-to-s3/commit/e0e647d419215b6a7e562dd64bdbfcd58443952d
