### ISSUE TITLE
[Error: Cannot initiate transfer]

### ISSUE THREAD

**Issue by aavileli** [markitx/dynamo-backup-to-s3#9]
Starting to copy table db_test
Error backing up undefined
{ table: 'db_test',
  err: [Error: Cannot initiate transfer] }
Error backing up db_test
{ tableName: 'db_test',
  error: [Error: Cannot initiate transfer] }
/nodejs/dynamodb/node_modules/dynamo-backup-to-s3/node_modules/s3-streaming-upload/node_modules/aws-sdk/lib/request.js:30
            throw err;
                  ^
ReferenceError: stopOnFailure is not defined
    at /nodejs/dynamodb/node_modules/dynamo-backup-to-s3/lib/dynamo-backup.js:113:29
    at Uploader.<anonymous> (/nodejs/dynamodb/node_modules/dynamo-backup-to-s3/lib/dynamo-backup.js:63:16)
    at Uploader.emit (events.js:107:17)
    at Response.<anonymous> (/nodejs/dynamodb/node_modules/dynamo-backup-to-s3/node_modules/s3-streaming-upload/lib/uploader.js:71:17)
    at Request.<anonymous> (/nodejs/dynamodb/node_modules/dynamo-backup-to-s3/node_modules/s3-streaming-upload/node_modules/aws-sdk/lib/request.js:353:18)
    at Request.callListeners (/nodejs/dynamodb/node_modules/dynamo-backup-to-s3/node_modules/s3-streaming-upload/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/nodejs/dynamodb/node_modules/dynamo-backup-to-s3/node_modules/s3-streaming-upload/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/nodejs/dynamodb/node_modules/dynamo-backup-to-s3/node_modules/s3-streaming-upload/node_modules/aws-sdk/lib/request.js:595:14)
    at Request.transition (/nodejs/dynamodb/node_modules/dynamo-backup-to-s3/node_modules/s3-streaming-upload/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/nodejs/dynamodb/node_modules/dynamo-backup-to-s3/node_modules/s3-streaming-upload/node_modules/aws-sdk/lib/state_machine.js:14:12)

script: 
var DynamoBackup = require('dynamo-backup-to-s3');

var backup = new DynamoBackup({
    includedTables: ['db_test'],
    bucket: "dynamodb-backup",
    readPercentage: .9,
    awsAccessKey: "xxxx",
    awsSecretKey: "xxxx",
    awsSecretKey: "us-west-1"
});

backup.on('error', function(data) {
    console.log('Error backing up ' + data.tableName);
    console.log(data);
});

backup.on('start-backup', function(tableName) {
    console.log('Starting to copy table ' + tableName);
});

backup.on('end-backup', function(tableName) {
    console.log('Done copying table ' + tableName);
});

backup.backupAllTables(function() {
    console.log('Finished backing up DynamoDB');
});

Module versions: 
├─┬ dynamo-backup-to-s3@0.1.8
│ ├── async@0.9.2
│ ├─┬ aws-sdk@2.0.31
│ │ ├─┬ xml2js@0.2.6
│ │ │ └── sax@0.4.2
│ │ └── xmlbuilder@0.4.2
│ ├── commander@2.5.1
│ ├── moment@2.8.4
│ ├─┬ s3-streaming-upload@0.1.17
│ │ ├─┬ aws-sdk@2.1.50
│ │ │ ├── sax@0.5.3
│ │ │ ├── xml2js@0.2.8
│ │ │ └── xmlbuilder@0.4.2
│ │ └─┬ readable-stream@1.0.33
│ │   ├── core-util-is@1.0.1
│ │   ├── inherits@2.0.1
│ │   ├── isarray@0.0.1
│ │   └── string_decoder@0.10.31
│ └── underscore@1.7.0

**Comment by dylanlingelbach** [comment]
@aavileli - thanks for the report. Just pushed a fix and published version 0.1.9.

**Comment by aavileli** [comment]
@dylanlingelbach thanks that fixed it

**Comment by GreyEcologist** [comment]
Hey, I'm getting a similar error, I'm wondering if it's policy issue, I have full access for S3 and DynamoDB, do I need other permissions?

here's the error below ( i added some console.logs to see where the error was) :

```
START RequestId: 3e9af9a8-9ada-11e5-84fb-d732598ecf7e Version: $LATEST
2015-12-04T22:56:25.049Z	3e9af9a8-9ada-11e5-84fb-d732598ecf7e	backupTable failed celebInfo error is Error: Cannot initiate transfer
2015-12-04T22:56:25.049Z	3e9af9a8-9ada-11e5-84fb-d732598ecf7e	Error backing up undefined
2015-12-04T22:56:25.066Z	3e9af9a8-9ada-11e5-84fb-d732598ecf7e	backupAllTables failed error is Error: Cannot initiate transfer
2015-12-04T22:56:25.066Z	3e9af9a8-9ada-11e5-84fb-d732598ecf7e	Error backing up celebInfo
2015-12-04T22:56:25.066Z	3e9af9a8-9ada-11e5-84fb-d732598ecf7e	[Error: Cannot initiate transfer]
2015-12-04T22:56:25.068Z	3e9af9a8-9ada-11e5-84fb-d732598ecf7e	Error: Callback was already called.
    at /var/task/node_modules/dynamo-backup-to-s3/node_modules/async/lib/async.js:30:31
    at /var/task/node_modules/dynamo-backup-to-s3/lib/dynamo-backup.js:126:36
    at Uploader.<anonymous> (/var/task/node_modules/dynamo-backup-to-s3/lib/dynamo-backup.js:65:16)
    at Uploader.emit (events.js:95:17)
    at Response.<anonymous> (/var/task/node_modules/dynamo-backup-to-s3/node_modules/s3-streaming-upload/lib/uploader.js:71:17)
    at Request.<anonymous> (/var/task/node_modules/dynamo-backup-to-s3/node_modules/s3-streaming-upload/node_modules/aws-sdk/lib/request.js:353:18)
    at Request.callListeners (/var/task/node_modules/dynamo-backup-to-s3/node_modules/s3-streaming-upload/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/var/task/node_modules/dynamo-backup-to-s3/node_modules/s3-streaming-upload/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/task/node_modules/dynamo-backup-to-s3/node_modules/s3-streaming-upload/node_modules/aws-sdk/lib/request.js:595:14)
    at Request.transition (/var/task/node_modules/dynamo-backup-to-s3/node_modules/s3-streaming-upload/node_modules/aws-sdk/lib/request.js:21:10)
END RequestId: 3e9af9a8-9ada-11e5-84fb-d732598ecf7e
REPORT RequestId: 3e9af9a8-9ada-11e5-84fb-d732598ecf7e	Duration: 208.05 ms	Billed Duration: 300 ms 	Memory Size: 256 MB	Max Memory Used: 19 MB	
Process exited before completing request
```

**Comment by GreyEcologist** [comment]
by the way, I traced the error to a function inside the uploader.js:

```
  Uploader.prototype.initiateTransfer = function() {
    var _this = this;
    if (this.initializing === false) {
      this.initializing = true;
      return this.getNewClient().createMultipartUpload(this.objectParams, function(err, data) {
        _this.initializing = false;
        if (err) {
          _this.emit('failed', new Error("Cannot initiate transfer"));
          _this.emit('error', err);
          return typeof _this.cb === "function" ? _this.cb(err) : void 0;
        }
        _this.uploadId = data.UploadId;
        _this.initiated = true;
        return _this.emit('initiated', _this.uploadId);
      });
    }
  };
```

the error itself is: 
```Callback was already called```

**Comment by dylanlingelbach** [comment]
@GreyEcologist - This error tends to indicate there is a permissioning issue. Does a simple read from Dynamo from the table you are backing up and and write to S3 to the bucket you are saving to work in lambda?

**Comment by GreyEcologist** [comment]
@dylanlingelbach yep, I'm able to do that with the current role, not sure if that helps, but I'm getting a different error alternatively, but it considers the backup done:

```
2015-12-08T02:47:21.095Z	004f3ffb-9d56-11e5-baba-6bbd4fff05e7	tables [ 'celebInfo' ]
2015-12-08T02:47:21.097Z	004f3ffb-9d56-11e5-baba-6bbd4fff05e7	Starting to copy table celebInfo
2015-12-08T02:47:21.774Z	004f3ffb-9d56-11e5-baba-6bbd4fff05e7	backupTable failed celebInfo error is Error: Cannot initiate transfer
2015-12-08T02:47:21.774Z	004f3ffb-9d56-11e5-baba-6bbd4fff05e7	undefined
2015-12-08T02:47:21.775Z	004f3ffb-9d56-11e5-baba-6bbd4fff05e7	backupAllTables failed error is Error: Cannot initiate transfer
2015-12-08T02:47:21.775Z	004f3ffb-9d56-11e5-baba-6bbd4fff05e7	[Error: Cannot initiate transfer]
2015-12-08T02:47:21.775Z	004f3ffb-9d56-11e5-baba-6bbd4fff05e7	Finished backing up DynamoDB
END RequestId: 004f3ffb-9d56-11e5-baba-6bbd4fff05e7
```

**Comment by dylanlingelbach** [comment]
@GreyEcologist - can you try backing up a single table instead of all to see if that gives more info?
